# Generated by Django 3.2.14 on 2022-11-19 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='divina_pagina_inicio',
            new_name='Divina_Pagina',
        ),
    ]
