# Generated by Django 3.2.14 on 2022-11-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_divina_pagina_inicio_divina_pagina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divina_pagina',
            name='slug',
            field=models.CharField(max_length=123),
        ),
    ]
